begin;
create extension if not exists pgtap with schema extensions;
select plan(38);

select has_type('public','curriculum_item_status','curriculum lifecycle enum exists');
select has_type('public','curriculum_release_mode','curriculum release enum exists');
select has_type('public','lesson_content_kind','lesson content enum exists');
select has_type('public','lesson_completion_mode','lesson completion enum exists');
select has_type('public','curriculum_entity_type','curriculum entity enum exists');
select has_type('public','curriculum_editor_event_type','curriculum audit enum exists');
select ok((select array_agg(enumlabel::text order by enumsortorder) from pg_enum where enumtypid='public.curriculum_item_status'::regtype)=array['draft','published','archived']::text[],'curriculum statuses are closed');
select ok((select array_agg(enumlabel::text order by enumsortorder) from pg_enum where enumtypid='public.curriculum_release_mode'::regtype)=array['immediate','scheduled','drip','after_prerequisites']::text[],'release modes are closed');
select has_table('public','module_prerequisites','module prerequisites table exists');
select has_table('public','lesson_prerequisites','lesson prerequisites table exists');
select has_table('public','curriculum_editor_events','curriculum audit table exists');
select ok((select bool_and(relrowsecurity and relforcerowsecurity) from pg_class where oid in ('public.module_prerequisites'::regclass,'public.lesson_prerequisites'::regclass,'public.curriculum_editor_events'::regclass)),'new curriculum tables force RLS');
select col_not_null('public','modulos','status','module status is required');
select col_not_null('public','modulos','version','module optimistic version is required');
select col_not_null('public','modulos','release_mode','module release mode is required');
select col_not_null('public','aulas','status','lesson status is required');
select col_not_null('public','aulas','version','lesson optimistic version is required');
select col_not_null('public','aulas','content_kind','lesson content kind is required');
select col_not_null('public','aulas','completion_mode','lesson completion mode is required');
select col_type_is('public','aulas','completion_percent','smallint','lesson completion percent uses smallint');
select has_fk('public','module_prerequisites','module prerequisites use foreign keys');
select has_fk('public','lesson_prerequisites','lesson prerequisites use foreign keys');
select has_index('public','modulos','modulos_course_status_order_idx','module listing is indexed');
select has_index('public','aulas','aulas_module_status_order_idx','lesson listing is indexed');
select has_index('public','module_prerequisites','module_prerequisites_reverse_idx','module reverse dependencies are indexed');
select has_index('public','lesson_prerequisites','lesson_prerequisites_reverse_idx','lesson reverse dependencies are indexed');
select is((select count(*)::integer from pg_trigger where not tgisinternal and tgname='modulos_set_curriculum_lifecycle'),1,'module lifecycle trigger exists once');
select is((select count(*)::integer from pg_trigger where not tgisinternal and tgname='aulas_set_curriculum_lifecycle'),1,'lesson lifecycle trigger exists once');
select ok(not has_table_privilege('authenticated','public.modulos','INSERT') and not has_table_privilege('authenticated','public.modulos','UPDATE') and not has_table_privilege('authenticated','public.modulos','DELETE'),'authenticated cannot mutate modules directly');
select ok(not has_table_privilege('authenticated','public.aulas','INSERT') and not has_table_privilege('authenticated','public.aulas','UPDATE') and not has_table_privilege('authenticated','public.aulas','DELETE'),'authenticated cannot mutate lessons directly');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and not p.prosecdef and p.proname in ('create_module','update_module','set_module_prerequisites','reorder_modules','archive_module','delete_module','duplicate_module','create_lesson','update_lesson','set_lesson_prerequisites','reorder_lessons','move_lesson','duplicate_lesson','archive_lesson','delete_lesson','archive_lesson_material')),16,'curriculum exposes sixteen invoker wrappers');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef),0,'no public security definer exists');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('create_module','update_module','set_module_prerequisites','reorder_modules','archive_module','delete_module','duplicate_module','create_lesson','update_lesson','set_lesson_prerequisites','reorder_lessons','move_lesson','duplicate_lesson','archive_lesson','delete_lesson','archive_lesson_material') and has_function_privilege('anon',p.oid,'EXECUTE')),0,'anonymous cannot invoke curriculum wrappers');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('create_module','update_module','set_module_prerequisites','reorder_modules','archive_module','delete_module','duplicate_module','create_lesson','update_lesson','set_lesson_prerequisites','reorder_lessons','move_lesson','duplicate_lesson','archive_lesson','delete_lesson','archive_lesson_material') and has_function_privilege('authenticated',p.oid,'EXECUTE')),16,'authenticated may reach wrappers and backend role checks');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.prosecdef and p.proconfig is distinct from array['search_path=""']::text[]),0,'all private security definers fix an empty search path');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename in ('module_prerequisites','lesson_prerequisites','curriculum_editor_events')),3,'new curriculum tables expose only admin read policies');
select is((select count(*)::integer from (select tablename,roles,cmd from pg_policies where schemaname='public' and permissive='PERMISSIVE' group by tablename,roles,cmd having count(*)>1) duplicate_policies),0,'curriculum introduces no overlapping permissive policies');
select ok(not exists(select 1 from information_schema.role_table_grants where grantee='anon' and table_schema='public' and table_name in ('module_prerequisites','lesson_prerequisites','curriculum_editor_events')),'anonymous has no curriculum table privileges');

select * from finish();
rollback;
