const rows = `
public/home|public|/|Index
public/contact|public|/contato|Contact
public/certificate|public|/certificado|CertificateValidation
public/login|public|/login|Login
public/register|public|/matricule-se|Register
public/forgot-password|public|/esqueceu-senha|ForgotPassword
public/reset-password|public|/redefinir-senha|ResetPassword
public/verify-email|public|/verificar-email|VerifyEmail
public/verified|public|/verificado|Verified
public/access-denied|public|/acesso-negado|AccessDenied
public/not-found|public|/preview-404|NotFound
student/dashboard|student|/aluno|StudentPortal:dashboard
student/courses|student|/aluno/cursos|StudentPortal:courses
student/course|student|/aluno/cursos/11111111-1111-4111-8111-111111111111|StudentPortal:course
student/modules|student|/aluno/cursos/11111111-1111-4111-8111-111111111111|StudentPortal:course
student/lessons|student|/aluno/cursos/11111111-1111-4111-8111-111111111111|StudentPortal:course
student/lesson-video|student|/aula/22222222-2222-4222-8222-222222222222|Lesson
student/lesson-text|student|/aula/33333333-3333-4333-8333-333333333333|Lesson
student/materials|student|/aluno/biblioteca|StudentPortal:library
student/library|student|/aluno/biblioteca|StudentPortal:library
student/favorites|student|/aluno/favoritos|StudentFavorites
student/certificates|student|/aluno/certificados|Certificates
student/products|student|/aluno/produtos|MyDigitalProducts:student
student/orders|student|/aluno/pedidos|StudentPortal:orders
student/payments|student|/aluno/pagamentos|StudentPortal:payments
student/notifications|student|/aluno/notificacoes|StudentNotifications
student/support|student|/aluno/suporte|StudentSupport
student/history|student|/aluno/historico|StudentPortal:history
student/profile|student|/aluno/perfil|StudentPortal:profile
student/profile-edit|student|/aluno/perfil/editar|EditProfile:student
student/preferences|student|/aluno/preferencias|StudentCommunicationPreferences
student/privacy|student|/aluno/privacidade|StudentPrivacyRights
admin/dashboard|admin|/admin|AdminDashboard
admin/courses|admin|/admin/cursos|CoursesAdmin
admin/course-new|admin|/admin/cursos/novo|CourseEditor
admin/course-edit|admin|/admin/cursos/11111111-1111-4111-8111-111111111111/editar|CourseEditor
admin/course-preview|admin|/admin/cursos/11111111-1111-4111-8111-111111111111/preview|CoursePreview
admin/curriculum|admin|/admin/cursos/11111111-1111-4111-8111-111111111111/curriculo|CourseCurriculum
admin/modules|admin|/admin/cursos/11111111-1111-4111-8111-111111111111/curriculo|CourseCurriculum
admin/lessons|admin|/admin/cursos/11111111-1111-4111-8111-111111111111/curriculo|CourseCurriculum
admin/module-editor|admin|/admin/cursos/11111111-1111-4111-8111-111111111111/curriculo|CourseCurriculum
admin/lesson-editor|admin|/admin/cursos/11111111-1111-4111-8111-111111111111/curriculo|CourseCurriculum
admin/assets|admin|/admin/cursos/11111111-1111-4111-8111-111111111111/curriculo|CourseCurriculum
admin/products|admin|/admin/produtos|DigitalProductsAdmin
admin/payments|admin|/admin/pagamentos|PaymentsAdmin
admin/affiliates|admin|/admin/afiliados|AffiliatesAdmin
admin/students|admin|/admin/alunos|StudentsAdmin
admin/academic|admin|/admin/academico|AcademicAnalyticsAdmin
admin/contacts|admin|/admin/contatos|ContactsAdmin
admin/support|admin|/admin/suporte|SupportAdmin
admin/privacy|admin|/admin/privacidade|PrivacyRightsAdmin
admin/errors|admin|/admin/erros|FrontendErrorsAdmin
affiliate/no-profile|affiliate|/afiliado|AffiliatePortal
affiliate/pending|affiliate|/afiliado|AffiliatePortal
affiliate/suspended|affiliate|/afiliado|AffiliatePortal
affiliate/active|affiliate|/afiliado#affiliate-overview|AffiliatePortal
affiliate/offers|affiliate|/afiliado#affiliate-offers|AffiliatePortal
affiliate/links|affiliate|/afiliado#affiliate-links|AffiliatePortal
affiliate/performance|affiliate|/afiliado#affiliate-clicks|AffiliatePortal
affiliate/commissions|affiliate|/afiliado#affiliate-commissions|AffiliatePortal
affiliate/payouts|affiliate|/afiliado#affiliate-payouts|AffiliatePortal
affiliate/events|affiliate|/afiliado#affiliate-events|AffiliatePortal
commerce/courses|commerce|/cursos|CourseStorefront
commerce/marketplace|commerce|/marketplace|DigitalMarketplace
commerce/marketplace-empty|commerce|/marketplace|DigitalMarketplace
commerce/products|commerce|/meus-produtos|MyDigitalProducts
commerce/checkout-processing|commerce|/pagamento-sucesso?status=processing|PaymentSuccess
commerce/checkout-error|commerce|/pagamento-sucesso?status=error|PaymentSuccess
commerce/payment-success|commerce|/pagamento-sucesso?status=paid|PaymentSuccess
commerce/payment-expired|commerce|/pagamento-sucesso?status=expired|PaymentSuccess
commerce/payment-cancelled|commerce|/pagamento-sucesso?status=cancelled|PaymentSuccess
commerce/payment-refunded|commerce|/pagamento-sucesso?status=refunded|PaymentSuccess
commerce/payment-chargeback|commerce|/pagamento-sucesso?status=chargeback|PaymentSuccess
`.trim().split("\n");
export const SURFACES = rows.map((row) => {
  const [slug, area, route, component] = row.split("|");
  return Object.freeze({ slug, area, route, component });
});
