// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjzcxdzigvfzmnarzqrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqemN4ZHppZ3Zmem1uYXJ6cXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTMyOTYsImV4cCI6MjA2NTc2OTI5Nn0.wwBW0u8RBUjBZPXAYo2uia0zTJx6kAjmZJEvWU_shAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);